# Generated by Django 5.0.6 on 2024-07-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_remove_post_published_tage_post_tags_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="tittle",
            new_name="title",
        ),
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(to="blog.tag"),
        ),
    ]
