# Generated by Django 5.0.6 on 2024-07-15 13:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0008_alter_post_image"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
