# Generated by Django 5.0.6 on 2024-07-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0010_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="comment",
        ),
        migrations.AddField(
            model_name="comment",
            name="username",
            field=models.CharField(max_length=120, null=True),
        ),
    ]
