# Generated by Django 5.0.6 on 2024-08-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0011_remove_comment_comment_comment_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="username",
            field=models.CharField(default="", max_length=120),
            preserve_default=False,
        ),
    ]
