# Generated by Django 5.0.6 on 2024-08-25 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BookCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("slug", models.SlugField(blank=True, default="")),
                ("thumbnail", models.ImageField(upload_to="")),
                ("added_date", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField(blank=True, null=True)),
                ("title", models.CharField(max_length=250)),
                ("description", models.TextField()),
                ("thumbnail", models.ImageField(upload_to="")),
                ("publication_name", models.CharField(max_length=250)),
                ("file", models.TextField()),
                ("edition", models.CharField(max_length=100)),
                ("discount_flag", models.BooleanField(default=False)),
                (
                    "discounted_price",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("added_date", models.DateField(auto_now_add=True)),
                ("updated_date", models.DateField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_free", models.BooleanField(default=False)),
                ("preview", models.TextField()),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="book.bookcategory",
                    ),
                ),
            ],
        ),
    ]
