# Generated by Django 5.0.6 on 2024-08-26 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookcategory",
            name="slug",
        ),
        migrations.AddField(
            model_name="book",
            name="slug",
            field=models.SlugField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="book",
            name="file",
            field=models.FileField(upload_to="uploads/"),
        ),
    ]
